<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX4JwNhp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX4JwNhp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX4JwNhp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX4JwNhp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX4JwNhp\App_KernelDevDebugContainer([
    'container.build_hash' => 'X4JwNhp',
    'container.build_id' => '63d947fd',
    'container.build_time' => 1643611020,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX4JwNhp');
